name: Format and Push Changes

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - '**.json'

jobs:
  format_and_push_changes:
    name: Format and Push Changes
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and format files
        run: |
          sudo apt-get install -y dos2unix curl vim git npm tree gifsicle
          curl -sSL https://git.io/JcGER | /bin/bash
          npm install -g markdownlint-cli2
          find . -name "*.md" -exec dos2unix {} + -o -name "*.json" -exec dos2unix {} +

      - name: Cleanup and autocorrect
        run: |
          /bin/bash .github/script/find_sed_cleanup.sh
          autocorrect --fix

      - name: Install dependencies and format files
        run: |
          find . -maxdepth 1 -type d \( -name "*-先知社区" -o -name "*-少数派" -o -name "奇安信攻防社区-*" \) -exec sh -c 'mv -f "$0" "./${0##*/}"' {} \;
          find . -name "*-先知社区" -type d -maxdepth 1 -exec mv -f {} 先知社区/ \;
          find . -name "奇安信攻防社区-*" -type d -maxdepth 1 -exec mv -f {} 奇安信攻防社区/ \;
          find . -name "*-少数派" -type d -maxdepth 1 -exec mv -f {} 少数派/ \;

      - name: Compress images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.DOCS_PUSH_TOKEN }}
          compressOnly: true
          jpegQuality: '60'
          jpegProgressive: false
          pngQuality: '60'
          webpQuality: '60'

      - name: Commit files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git reflog expire --expire=now --all 
          git gc --prune=now --aggressive
          git add -A
          git commit -m "Autocorrect Format" -a || exit 0  # If no changes, exit without error

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.DOCS_PUSH_TOKEN }}
          branch: ${{ github.ref }}
